import json

from app.database.connection import get_sqlite_engine
from app.database.metadata import discover_schema
from app.dq.engine import DQEngine
from app.llm.provider import get_llm
from app.incidents.models import IncidentAnalysis
from app.incidents.service import save_incidents


def discover_database(state):
    print("=" * 70)
    print("DISCOVERING DATABASE")
    print("=" * 70)

    engine = get_sqlite_engine(state["db_path"])
    schema = discover_schema(engine)

    print("Tables discovered:", len(schema))

    return {
        "schema": schema,
        "status": "DATABASE_DISCOVERED",
    }


def run_dq_scan(state):
    print("=" * 70)
    print("RUNNING DQ SCAN")
    print("=" * 70)

    engine = get_sqlite_engine(state["db_path"])
    dq_engine = DQEngine(engine)

    findings = dq_engine.run()

    print("DQ findings generated:", len(findings))

    return {
        "findings": findings,
        "status": "DQ_SCAN_COMPLETED",
    }


def select_candidates(state):
    findings = state.get("findings", [])

    print("=" * 70)
    print("SELECTING CANDIDATES")
    print("=" * 70)

    print("Findings received:", len(findings))

    severity_counts = {}

    for finding in findings:
        severity = finding.get("severity", "UNKNOWN")
        severity_counts[severity] = severity_counts.get(severity, 0) + 1

    print("Severity counts:", severity_counts)

    candidates = [
        finding
        for finding in findings
        if finding.get("severity") in {"HIGH", "MEDIUM"}
    ]

    print("Candidates selected:", len(candidates))

    return {
        "candidate_findings": candidates,
        "status": "CANDIDATES_SELECTED",
    }


def analyze_findings(state):
    findings = state.get("candidate_findings", [])

    print("=" * 70)
    print("ANALYZING FINDINGS WITH LLM")
    print("=" * 70)

    print("Candidate findings received:", len(findings))

    if not findings:
        return {
            "analyzed_issues": [],
            "status": "LLM_ANALYSIS_COMPLETED",
        }

    print("Connecting to LLM...")

    llm = get_llm()

    print("LLM connection created.")

    structured_llm = llm.with_structured_output(IncidentAnalysis)

    prompt = f"""
You are a Data Quality incident analyst.

Analyze the following Data Quality findings.

Your responsibilities:

1. Group related findings into meaningful business-level incidents.
2. Do NOT create one incident for every finding.
3. Identify likely root causes.
4. Determine business impact.
5. Recommend remediation.
6. Use only evidence contained in the findings.
7. Do not invent row counts, columns, tables, or facts.
8. Prefer a small number of meaningful incidents over many duplicate incidents.
9. Give higher priority to HIGH severity findings.
10. Related NULL, consistency, duplicate, and business-rule findings may belong
    to the same incident if they indicate the same underlying problem.
11. Do not describe a business-rule violation as a formatting problem unless
    the evidence explicitly indicates a formatting problem.
12. Evidence must contain concrete facts from the supplied findings.

DQ FINDINGS:

{json.dumps(findings, indent=2, default=str)}

Return structured incidents.
"""

    print("Sending findings to LLM...")

    result = structured_llm.invoke(prompt)

    print("LLM analysis completed.")

    analyzed_issues = [
        incident.model_dump()
        for incident in result.incidents
    ]

    print("Incidents generated by LLM:", len(analyzed_issues))

    return {
        "analyzed_issues": analyzed_issues,
        "status": "LLM_ANALYSIS_COMPLETED",
    }


def save_generated_incidents(state):
    incidents = state.get("analyzed_issues", [])

    print("=" * 70)
    print("SAVING INCIDENTS")
    print("=" * 70)

    print("Incidents received:", len(incidents))

    if not incidents:
        print("No incidents to save.")

        return {
            "incidents": [],
            "status": "INCIDENTS_SAVED",
        }

    engine = get_sqlite_engine(state["db_path"])

    saved = save_incidents(
        engine=engine,
        incidents=incidents,
    )

    print("Incidents saved:", len(saved))

    return {
        "incidents": saved,
        "status": "INCIDENTS_SAVED",
    }